// SPDX-License-Identifier: LGPL-3.0-or-later

package io.github.thomasjoleary.toxicsurface.registry;

import io.github.thomasjoleary.toxicsurface.ToxicSurface;
import java.util.function.Consumer;
import java.util.function.Supplier;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.material.FlowingFluid;
import net.minecraft.world.level.material.Fluid;
import net.neoforged.neoforge.client.extensions.common.IClientFluidTypeExtensions;
import net.neoforged.neoforge.fluids.BaseFlowingFluid;
import net.neoforged.neoforge.fluids.FluidType;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.NeoForgeRegistries;

/**
 * Toxic sludge — a real custom fluid (DESIGN.md §3 Toxic sludge). Registers the
 * {@link FluidType} plus the still/flowing {@link BaseFlowingFluid} pair. Behaves
 * like water (flows, swimmable, drownable); contact damage, organic-item destruction
 * and Create fluid-handler integration are layered on in later increments.
 */
public final class ModFluids {
    public static final DeferredRegister<FluidType> FLUID_TYPES =
            DeferredRegister.create(NeoForgeRegistries.Keys.FLUID_TYPES, ToxicSurface.MODID);
    public static final DeferredRegister<Fluid> FLUIDS = DeferredRegister.create(Registries.FLUID, ToxicSurface.MODID);

    // Sludge fluid textures (animated still/flow strips + side overlay, generated by
    // tools/textures/gen_sludge.py and stitched onto the block atlas via atlases/blocks.json).
    // These ids MUST be non-null regardless: NeoForge's FluidSpriteCache NPEs on a null texture key
    // while tesselating the liquid (the four "Tesselating liquid in world" crash reports).
    private static final ResourceLocation SLUDGE_STILL =
            ResourceLocation.fromNamespaceAndPath(ToxicSurface.MODID, "block/sludge_still");
    private static final ResourceLocation SLUDGE_FLOW =
            ResourceLocation.fromNamespaceAndPath(ToxicSurface.MODID, "block/sludge_flow");
    private static final ResourceLocation SLUDGE_OVERLAY =
            ResourceLocation.fromNamespaceAndPath(ToxicSurface.MODID, "block/sludge_overlay");
    private static final int SLUDGE_TINT = 0xFF4A5D23; // opaque toxic olive-green

    public static final Supplier<FluidType> SLUDGE_TYPE = FLUID_TYPES.register(
            "sludge",
            () ->
                    new FluidType(FluidType.Properties.create()
                            .density(3000) // denser/heavier-feeling than water
                            .viscosity(6000) // flows sluggishly
                            .canSwim(true)
                            .canDrown(true)) {
                        // initializeClient is only invoked client-side, so the client-only IClientFluidTypeExtensions
                        // never classloads on a dedicated server (the standard NeoForge 1.21.1 fluid-render hook).
                        @Override
                        public void initializeClient(Consumer<IClientFluidTypeExtensions> consumer) {
                            consumer.accept(new IClientFluidTypeExtensions() {
                                @Override
                                public ResourceLocation getStillTexture() {
                                    return SLUDGE_STILL;
                                }

                                @Override
                                public ResourceLocation getFlowingTexture() {
                                    return SLUDGE_FLOW;
                                }

                                @Override
                                public ResourceLocation getOverlayTexture() {
                                    return SLUDGE_OVERLAY;
                                }

                                @Override
                                public int getTintColor() {
                                    return SLUDGE_TINT;
                                }
                            });
                        }
                    });

    public static final Supplier<FlowingFluid> SLUDGE =
            FLUIDS.register("sludge", () -> new BaseFlowingFluid.Source(ModFluids.PROPERTIES));
    public static final Supplier<FlowingFluid> SLUDGE_FLOWING =
            FLUIDS.register("flowing_sludge", () -> new BaseFlowingFluid.Flowing(ModFluids.PROPERTIES));

    // Suppliers keep this lazy so it can reference the fluids/block/bucket before they register.
    public static final BaseFlowingFluid.Properties PROPERTIES = new BaseFlowingFluid.Properties(
                    SLUDGE_TYPE, SLUDGE, SLUDGE_FLOWING)
            .slopeFindDistance(2)
            .levelDecreasePerBlock(2)
            .block(() -> ModBlocks.SLUDGE_BLOCK.get())
            .bucket(() -> ModItems.SLUDGE_BUCKET.get());

    private ModFluids() {}
}
